name: 1-minute-cron
on:
  schedule:
    - cron: '* * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our service API route
        run: |
          curl --request POST \
          --url 'https://shop-service-api.vercel.app/api/crystallize/run'
